# Site settings
title: DuanXu's Blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog!
baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "http://www.duanxu.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate, jekyll-coffeescript]
    

# comments
disqus: doodle777

# author info
# add your appropriate info here
author: # your name
bio:    # your bio
email: duanxu@outlook.com
email_md5: # md5 hash of your email
twitter_username: Dr_DuanXu
github_username: doodle777

# Theming options
# These settings are mandatory.
# theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
