# Site settings
name: Less Or More
email: duanxu@outlook.com
author: Duan Xu
url: http://www.duanxu.science
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/doodle777/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: MAY THE FORCE BE WITH YOU.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: rouge

# Build settings
markdown: kramdown

gems: [jekyll-paginate, jekyll-coffeescript]

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
